package es.altia.bne.postulante.infraestucture.persistence.repository.entity;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/*
 * PerClave generated by hbm2java
 */
@Entity
@Table(name = "PER_CLAVE")
public class PerClave {

    private Long id;
    private PerPersonas perPersonas;
    private Date fecUltAcceso;
    private Integer numFallosAcceso;
    private Date fecAlta;
    private Date fecModif;
    private String estado;
    private String clave;
    private Date aceptacionUsoCondiciones;

    public PerClave() {
    }

    public PerClave(final long id) {
        this.id = id;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, precision = 18, scale = 0)
    public Long getId() {
        return this.id;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public PerPersonas getPerPersonas() {
        return this.perPersonas;
    }

    public void setPerPersonas(final PerPersonas perPersonas) {
        this.perPersonas = perPersonas;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FEC_ULT_ACCESO", length = 23)
    public Date getFecUltAcceso() {
        return this.fecUltAcceso;
    }

    public void setFecUltAcceso(final Date fecUltAcceso) {
        this.fecUltAcceso = fecUltAcceso;
    }

    @Column(name = "NUM_FALLOS_ACCESO")
    public Integer getNumFallosAcceso() {
        return this.numFallosAcceso;
    }

    public void setNumFallosAcceso(final Integer numFallosAcceso) {
        this.numFallosAcceso = numFallosAcceso;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FEC_ALTA", nullable = false, length = 23)
    public Date getFecAlta() {
        return this.fecAlta;
    }

    public void setFecAlta(final Date fecAlta) {
        this.fecAlta = fecAlta;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FEC_MODIF", length = 23)
    public Date getFecModif() {
        return this.fecModif;
    }

    public void setFecModif(final Date fecModif) {
        this.fecModif = fecModif;
    }

    @Column(name = "ESTADO", length = 1)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(final String estado) {
        this.estado = estado;
    }

    @Column(name = "CLAVE", length = 60)
    public String getClave() {
        return this.clave;
    }

    public void setClave(final String clave) {
        this.clave = clave;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ACEPTACION_USO_CONDICIONES")
    public Date getAceptacionUsoCondiciones() {
        return this.aceptacionUsoCondiciones;
    }

    public void setAceptacionUsoCondiciones(final Date aceptacionUsoCondiciones) {
        this.aceptacionUsoCondiciones = aceptacionUsoCondiciones;
    }

}
